use boto to create load balancer
Was using the aws-cli since `create_load_balancer` would throw:

    TypeError: create_load_balancer() takes at least 3 arguments (5
given)

Turns out you have to pass `zones=None` explicitly if you provide a
list of subnet.

╯°□°）╯︵ ┻━┻